#!/bin/bash

# Folder where this repository is
DIR=/home/$USER/.dotfiles

git submodule update --init --recursive

installfile() {
    SOURCE=$1
    TARGET=$2

    if [ ! -e $TARGET ]; then
        echo -e " * \e[33mLinking\e[39m: $SOURCE \t->\t $TARGET"
        ln -s $SOURCE $TARGET
    fi

}

mkdir -p ~/.config
for ENTRY in "$DIR/config"/*; do
    echo -e "[\e[32m.config\e[39m] update $ENTRY"
    installfile $ENTRY ~/.config/${ENTRY##*/}
done

for ENTRY in "$DIR/home"/*; do
    echo -e "[\e[32mhome\e[39m] update $ENTRY"
    installfile $ENTRY ~/.${ENTRY##*/}
done

echo -e "\n\e[01;34mFurther Setup Instructions\e[39m:"
cat setup_instructions
