# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Environment Variables
export HISTCONTROL="erasedups:ignorespace"
export EDITOR="vim"

# Hooks
[[ -f /usr/share/bash-completion/bash_completion ]] && source /usr/share/bash-completion/bash_completion

# Wal Colors
(cat ~/.cache/wal/sequences &)

# Shell Prompt Customization
BYELLOW='\[\033[01;33m\]'
PS_CLEAR='\[\033[0m\]'
export PS1="${BYELLOW}\u:\w${PS_CLEAR}$ "

# Aliases
alias ls='ls --color=auto'
alias ll='ls -lhA --color=auto'
alias grep='grep --color=auto'

shopt -s checkwinsize  # Let bash know when the terminal has been resized.

download_music() {
    yt-dlp -x --audio-format mp3 --audio-quality 320k $1
}
