[options]
HoldPkg = pacman glibc base linux linux-firmware
IgnorePkg =
IgnoreGroup = 
Architecture = auto
SigLevel = Required DatabaseOptional
Color
CheckSpace
VerbosePkgLists
ParallelDownloads = 6

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

#[multilib]
#Include = /etc/pacman.d/mirrorlist
