#
# pacman.conf
# by DesktopCoder1407
#

#
# GENERAL OPTIONS
#
[options]
Architecture = auto
HoldPkg     = pacman glibc
ParallelDownloads = 8
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional
Color
CheckSpace
VerbosePkgLists

#
# REPOSITORIES
#
[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

#[multilib]
#Include = /etc/pacman.d/mirrorlist
