# vim:fileencoding=utf-8:foldmethod=marker
# Hypridle Configuration

general {
	lock_cmd = pidof hyprlock || hyprlock
}

listener { # 5m, Dim Screen
	timeout = 300
	on-timeout = brightnessctl -s set 10
	on-resume = brightnessctl -r
}

listener { # 10m, Lock Screen
	timeout = 600
	on-timeout = loginctl lock-session
}

listener { # 12m, Turn off monitor
	timeout = 720
	on-timeout = hyprctl dispatch dpms off
	on-resume = hyprctl dispatch dpms on
}
