# vim:fileencoding=utf-8:foldmethod=marker
# Hyprlock Configuration

general {
    ignore_empty_input = true
}

background {
    monitor =
    path = 
    color = rgba(122b3eff)
}

# User Name
label {
    monitor =
    text = $USER
    color = rgba(ffffffff)
    font_size = 18
    font_family = Fira Code Nerd Font Proportional Light

    halign = center
    valign = center
    position = 0, 10
}

# Password
input-field {
    monitor =
    size = 350, 40
    outline_thickness = 0

    dots_size = 0.2
    dots_spacing = 0.1
    dots_center = true

    inner_color = rgba(ffffffff)
    font_color = rgba(000000ff)
    font_family = Fira Code Nerd Font Proportional

    fade_on_empty = false

    check_color = rgba(aaaaaaff)
    fail_color = rgba(aaaaaaff)
    fail_text = <i>Incorrect Password</i>

    halign = center
    valign = center
    position = 0, -40
}

# Time
label {
    monitor =
    text = cmd[update:30000] echo "$TIME"
    color = rgba(ffffffff)
    font_size = 48
    font_family = Fira Code Nerd Font Proportional Light

    halign = center
    valign = center
    position = 0, 350
}

# Date
label {
    monitor =
    text = cmd[update:30000] echo "$(date +"%A, %d %B, %Y")"
    color = rgba(ffffffff)
    font_size = 28
    font_family = Fira Code Nerd Font Proportional Light

    halign = center
    valign = center
    position = 0, 300
}

# Left Battery Display
label {
    monitor =
    text = cmd[update:5000] echo "$(acpi | grep -o "\w\?\w\?\w%" | sed "s/.\+%$/󰁹  &/")"
    color = rgba(ffffffff)
    font_size = 24
    font_family = Fira Code Nerd Font Proportional Regular

    halign = left
    valign = bottom
    position = 80, 45
}

# Right Weather Display
label {
    monitor =
    text = cmd[update:300000] echo "$(curl https://wttr.in/Warner%20Robins,%20GA?format=3)"
    color = rgba(ffffffff)
    font_size = 24
    font_family = Fira Code Nerd Font Proportional Regular

    halign = right
    valign = bottom
    position = -80, 45
}
