# vim:fileencoding=utf-8:foldmethod=marker
# Hyprlock Configuration
# By DesktopCoder1407

general {
    ignore_empty_input = true
}

background {
    monitor =
    path = 
    color = rgba(122b3eff)
}

input-field {
    monitor =
    size = 300, 50
    #outline_thickness = 4

    dots_size = 0.25 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.15 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    #dots_rounding = -1 # -1 default circle, -2 follow input-field rounding

    outer_color = rgba(000000ff)
    inner_color = rgba(adbcbcff)
    font_color = rgba(000000ff)
    font_family = Fira Code Nerd Font Proportional

    fade_on_empty = false
    #placeholder_text = <i>Input Password...</i>
    rounding = 0

    check_color = rgb(204, 136, 34)
    fail_color = rgb(204, 34, 34)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    fail_transition = 300

    capslock_color = -1
    swap_font_color = false # see below

    position = 0, -30
}

label { # Clock
    monitor =
    text = cmd[update:1000] echo "$(date +"%A %d %B") - $TIME"
    color = rgba(adbcbcff)
    font_size = 48
    font_family = Fira Code Nerd Font Proportional Semibold

    halign = right
    valign = bottom
    position = -80, 45
}

label { # Logged-in User Name
    monitor =
    text = $USER
    color = rgba(adbcbcff)
    font_size = 24
    font_family = Fira Code Nerd Font Proportional

    halign = center
    valign = center
    position = 0, 30
}
