# vim:fileencoding=utf-8:foldmethod=marker
# Hypridle Configuration
# By DesktopCoder1407

general {
    lock_cmd = pidof hyprlock || hyprlock
    unlock_cmd =
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on

    #ignore_debus_inhibit = false
    #ignore_systemd_inhibit = false
}

listener { # 2m, Dim Screen
    timeout = 120
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

listener { # 5m, Lock Screen
    timeout = 300
    on-timeout = loginctl lock-session
}

listener { # 5:30m, Turn off monitor
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener { # 15m, Suspend
    timeout = 900
    on-timeout = systemctl suspend
}
