title    Arch Linux
linux    /vmlinuz-linux
initrd   /amd-ucode.img
initrd   /initramfs-linux.img
options  root=PARTUUID=aa389be0-d7d7-9b41-8437-6e5ab638959d rw udev.log-priority=3 rd.udev.log-priority=3 mitigations=off quiet

# Possible Options
# vt.global_cursor_default=0 <-- disables blinking cursor
# nowatchdog <-- disables watchdog
